### ISSUE TITLE
"WARNING time_series and masks are not in the same space" even according to fslinfo they share same dimensions

### ISSUE THREAD

**Issue by JosZimmermann** [inm7/cbptools#2]
Hi,
I wanted to test your toolbox for rs-fmri data that were preprocessed using fmriprep. I have installed the toolbox via pip.

During validation using the following command:
cbptools create --config ./config_rsfmri.yaml --workdir /nfs/workdir/CBPtools_clustering

I get the error "WARNING time_series and masks are not in the same space" for all subjects even though when checking dimensions of the time series, masks and your default gray matter target mask they all share the same dimensions.

Here the output of fslinfo for these files:
**time series :**
data_type       FLOAT32
dim1            91
dim2            109
dim3            91
dim4            300
datatype        16
pixdim1         2.000000
pixdim2         2.000000
pixdim3         2.000000
pixdim4         2.000000
cal_max         3661.152100
cal_min         -294.926727
file_type       NIFTI-1+

**Seedmask:**
data_type       FLOAT32
dim1            91
dim2            109
dim3            91
dim4            1
datatype        16
pixdim1         2.000000
pixdim2         2.000000
pixdim3         2.000000
pixdim4         1.000000
cal_max         0.000000
cal_min         0.000000
file_type       NIFTI-1+

**Target mask  (default MNI152GM):**
data_type       FLOAT32
dim1            91
dim2            109
dim3            91
dim4            1
datatype        16
pixdim1         2.000000
pixdim2         2.000000
pixdim3         2.000000
pixdim4         0.000000
cal_max         0.000000
cal_min         0.000000
file_type       NIFTI-1+

Any idea why this error pops up?

Best wishes,
Josua

**Comment by nhjjr** [comment]
That bit of project set up runs the `imgs_equal_3d()` [function](https://github.com/inm7/cbptools/blob/34ca7945ccabd8670451a82cdd45a646981a166e/cbptools/image.py#L19), which checks if both the affine and shape (first 3 dimensions only) are identical. Since the dimensions match, I'm assuming that the affines don't. 

You can check this by installing `nibabel` (comes with cbptools, so just activating your cbptools virtual environment should work) and running the following in python3:

```python3
import nibabel as nib
img = nib.load('time_series.nii.gz');
img.affine
```

The output for the included target mask is:

```python3
array([[  -2.,    0.,    0.,   90.],
       [   0.,    2.,    0., -126.],
       [   0.,    0.,    2.,  -72.],
       [   0.,    0.,    0.,    1.]])
```

You can find more information about the coordinate systems and affines as implemented in nibabel [here](https://nipy.org/nibabel/coordinate_systems.html).
